name: ghaslah
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  dio: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  google_nav_bar: ^5.0.6
  hexcolor: ^3.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.18
  syncfusion_flutter_datepicker: ^20.4.53

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/jpg/
    - assets/json/car_list.json
  fonts:
    - family : NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf