name: ghaslah
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  dio: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  google_nav_bar: ^5.0.6
  hexcolor: ^3.0.1
  intl: ^0.18.0
  location: ^4.4.0
  material_floating_search_bar: ^0.3.7
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.18
  syncfusion_flutter_datepicker: ^22.1.36
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/jpg/
    - assets/json/car_list.json
  fonts:
    - family : NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf